import { strict as assert } from 'node:assert';
import { generateVerifier, POSTGRES_SCRAM_PARAMETERS, verifyPassword } from '../src/scram.ts';

/**
 * Verifiers generated by PostgreSQL 16 with:
 *     SET scram_iterations = <n>; CREATE ROLE r PASSWORD 'Clave de prueba 123!';
 *     SELECT rolpassword FROM pg_authid WHERE rolname = 'r';
 */
const POSTGRES_PASSWORD: string = 'Clave de prueba 123!';
const POSTGRES_VERIFIER_4096: string = 'SCRAM-SHA-256$4096:+0KaIrUzxRQ65WrIwT5YgA==$LoiRBk0KG7KFKgxhx6zpOuxBm/Bg2mTf25KAE4DU42o=:TwmB0BfnxCj5DEwLKhpqOGdedTrR7GojaiUlJdnTZzo=';
const POSTGRES_VERIFIER_10000: string = 'SCRAM-SHA-256$10000:bXiQmA68uJG0cJBCaYBwWQ==$HEIELoMOLtrOyMAxjrQ77KyYjxZw3dvfWOhhSkYOQsg=:nOFxeuaRue7rBtg/nIMZxCodpn+Yk16VjXQPEmuAVQY=';

const FORMAT: RegExp = /^SCRAM-SHA-256\$([0-9]+):([^$:]+)\$([^$:]+):([^$:]+)$/;

function partsOf(verifier: string): { iterations: number, salt: Buffer, storedKey: Buffer, serverKey: Buffer } {
    var parts: RegExpExecArray | null = FORMAT.exec(verifier);
    if (parts == null) {
        throw new Error('unexpected format: ' + verifier);
    }
    return {
        iterations: Number(parts[1]),
        salt: Buffer.from(parts[2], 'base64'),
        storedKey: Buffer.from(parts[3], 'base64'),
        serverKey: Buffer.from(parts[4], 'base64'),
    };
}

describe('scram', function (): void {

    describe('default parameters', function (): void {
        it('are the PostgreSQL ones', function (): void {
            assert.deepEqual(POSTGRES_SCRAM_PARAMETERS, { iterations: 4096, saltLength: 16 });
        });
    });

    describe('verifiers generated by PostgreSQL', function (): void {
        it('accepts the right password with 4096 iterations', async function (): Promise<void> {
            assert.equal(await verifyPassword(POSTGRES_PASSWORD, POSTGRES_VERIFIER_4096), true);
        });
        it('accepts the right password with 10000 iterations', async function (): Promise<void> {
            assert.equal(await verifyPassword(POSTGRES_PASSWORD, POSTGRES_VERIFIER_10000), true);
        });
        it('rejects a wrong password', async function (): Promise<void> {
            assert.equal(await verifyPassword('Clave de prueba 124!', POSTGRES_VERIFIER_4096), false);
        });
    });

    describe('generateVerifier', function (): void {
        it('uses the PostgreSQL format and default parameters', async function (): Promise<void> {
            var parts = partsOf(await generateVerifier('a password', POSTGRES_SCRAM_PARAMETERS));
            assert.equal(parts.iterations, 4096);
            assert.equal(parts.salt.length, 16);
            assert.equal(parts.storedKey.length, 32);
            assert.equal(parts.serverKey.length, 32);
        });
        it('honors changed parameters', async function (): Promise<void> {
            var verifier: string = await generateVerifier('a password', { iterations: 5000, saltLength: 32 });
            var parts = partsOf(verifier);
            assert.equal(parts.iterations, 5000);
            assert.equal(parts.salt.length, 32);
            assert.equal(await verifyPassword('a password', verifier), true);
        });
        it('uses a different salt each time', async function (): Promise<void> {
            var first: string = await generateVerifier('a password', POSTGRES_SCRAM_PARAMETERS);
            var second: string = await generateVerifier('a password', POSTGRES_SCRAM_PARAMETERS);
            assert.notEqual(first, second);
        });
        it('generates verifiers that can be verified back', async function (): Promise<void> {
            var verifier: string = await generateVerifier('another password: ~{}', POSTGRES_SCRAM_PARAMETERS);
            assert.equal(await verifyPassword('another password: ~{}', verifier), true);
            assert.equal(await verifyPassword('another password: ~{]', verifier), false);
        });
    });

    describe('malformed verifiers', function (): void {
        var cases: readonly (readonly [string, string])[] = [
            ['another algorithm', 'SCRAM-SHA-1$4096:+0KaIrUzxRQ65WrIwT5YgA==$LoiRBk0KG7KFKgxhx6zpOuxBm/Bg2mTf25KAE4DU42o=:TwmB0BfnxCj5DEwLKhpqOGdedTrR7GojaiUlJdnTZzo='],
            ['PostgreSQL md5', 'md5a3556571e93b0d20722ba62be61e8c2d'],
            ['zero iterations', 'SCRAM-SHA-256$0:+0KaIrUzxRQ65WrIwT5YgA==$LoiRBk0KG7KFKgxhx6zpOuxBm/Bg2mTf25KAE4DU42o=:TwmB0BfnxCj5DEwLKhpqOGdedTrR7GojaiUlJdnTZzo='],
            ['short stored key', 'SCRAM-SHA-256$4096:+0KaIrUzxRQ65WrIwT5YgA==$LoiRBk0KG7KFKgxhx6zpOuxBm/Bg2mTf:TwmB0BfnxCj5DEwLKhpqOGdedTrR7GojaiUlJdnTZzo='],
            ['missing server key', 'SCRAM-SHA-256$4096:+0KaIrUzxRQ65WrIwT5YgA==$LoiRBk0KG7KFKgxhx6zpOuxBm/Bg2mTf25KAE4DU42o='],
        ];
        cases.forEach(function ([description, verifier]: readonly [string, string]): void {
            it('throws: ' + description, async function (): Promise<void> {
                await assert.rejects(verifyPassword(POSTGRES_PASSWORD, verifier));
            });
        });
    });
});
