import { strict as assert } from 'node:assert';
import type { Pool } from 'pg';
import { createPgUserStore } from '../src/pg-stores.ts';
import { POSTGRES_SCRAM_PARAMETERS } from '../src/scram.ts';
import type { UserStore } from '../src/stores.ts';
import { addUser, isPrintableAscii, verifyCredentials } from '../src/users.ts';
import { prepareDatabase } from './database.ts';

describe('users', function (): void {
    var pool: Pool;
    var store: UserStore;

    before(async function (): Promise<void> {
        pool = await prepareDatabase();
        store = createPgUserStore(pool);
        await addUser(store, 'ana', 'ana password', POSTGRES_SCRAM_PARAMETERS);
    });

    after(async function (): Promise<void> {
        await pool.end();
    });

    it('stores a SCRAM-SHA-256 verifier', async function (): Promise<void> {
        var verifier: string | undefined = await store.findVerifier('ana');
        assert.match(verifier ?? '', /^SCRAM-SHA-256\$4096:/);
    });

    it('accepts the right password', async function (): Promise<void> {
        assert.equal(await verifyCredentials(store, 'ana', 'ana password', POSTGRES_SCRAM_PARAMETERS), true);
    });

    it('rejects a wrong password', async function (): Promise<void> {
        assert.equal(await verifyCredentials(store, 'ana', 'ana passwore', POSTGRES_SCRAM_PARAMETERS), false);
    });

    it('rejects an unknown user', async function (): Promise<void> {
        assert.equal(await verifyCredentials(store, 'bea', 'ana password', POSTGRES_SCRAM_PARAMETERS), false);
    });

    it('rejects non ASCII credentials at login', async function (): Promise<void> {
        assert.equal(await verifyCredentials(store, 'ana', 'contraseña', POSTGRES_SCRAM_PARAMETERS), false);
        assert.equal(await verifyCredentials(store, 'añа', 'ana password', POSTGRES_SCRAM_PARAMETERS), false);
    });

    it('refuses to create non ASCII users or passwords', async function (): Promise<void> {
        await assert.rejects(addUser(store, 'ñandú', 'password', POSTGRES_SCRAM_PARAMETERS), /printable ASCII/);
        await assert.rejects(addUser(store, 'bea', 'contraseña', POSTGRES_SCRAM_PARAMETERS), /printable ASCII/);
    });

    it('refuses to create an existing user', async function (): Promise<void> {
        await assert.rejects(addUser(store, 'ana', 'other', POSTGRES_SCRAM_PARAMETERS), /the user ana already exists/);
    });

    it('knows which users exist', async function (): Promise<void> {
        assert.equal(await store.exists('ana'), true);
        assert.equal(await store.exists('bea'), false);
    });

    it('accepts a verifier generated by PostgreSQL', async function (): Promise<void> {
        await pool.query("set scram_iterations = 4096; create role gate_one_test_role password 'role password'");
        try {
            var result = await pool.query<{ rolpassword: string }>("select rolpassword from pg_authid where rolname = 'gate_one_test_role'");
            assert.equal(await store.add('carla', result.rows[0].rolpassword), true);
            assert.equal(await verifyCredentials(store, 'carla', 'role password', POSTGRES_SCRAM_PARAMETERS), true);
        } finally {
            await pool.query('drop role gate_one_test_role');
        }
    });

    it('isPrintableAscii', function (): void {
        assert.equal(isPrintableAscii('a Z ~ !'), true);
        assert.equal(isPrintableAscii(''), false);
        assert.equal(isPrintableAscii('tab\there'), false);
        assert.equal(isPrintableAscii('ñ'), false);
    });
});
